meta:
  engine: 4.1.0

units:
  kx: u
  ky: u

points:
  key:
    padding: ky
    spread: 1kx
    tags: key
  zones:
    matrix: # of keys
      anchor:
        shift: [ 100, -100 ] # Fix KiCad placement
      # Use the pins closer to the keys for the rows, and the pins farther from the keys for the columns
      columns:
        outer:
          key:
            column_net: C0
        pinky:
          key:
            column_net: C1
        ring:
          key:
            stagger: 5
            column_net: C2
        middle:
          key:
            stagger: 10
            column_net: C3
        index:
          key:
            stagger: -5
            column_net: C4
        indexfar:
          key:
            stagger: -2.5
            column_net: C5
      rows:
        bottom:
          row_net: R2
        home:
          row_net: R1
        top:
          row_net: R0
    thumbs:
      columns:
        layer:
          key:
            splay: -15
            column_net: C4
        space:
          key:
            splay: -15
            shift: [ 3,-2 ]
            column_net: C5
      anchor:
        ref: matrix_index_bottom
        shift: [ 2,-ky - 3 ]
      rows:
        cluster:
          row_net: R3
    mcu:
      key.tags:
        - helper
      anchor:
        - ref: matrix_indexfar_top
          shift: [ u/2+18/2+1.6,u/2-33/2 ]
    screws_left:
      key.tags:
        - helper
        - screw
      key.padding: kx
      anchor:
        - ref: matrix_outer_bottom
          shift: [ 0.5 kx , 0.5 kx ]
      columns:
      rows:
        top:
        bottom:
    screws_right:
      key.tags:
        - helper
        - screw
      key.padding: kx
      anchor:
        - ref: matrix_indexfar_home
          shift: [ -0.5 kx + 1 , -0.5 kx + 1]
      columns:
      rows:
        top:
        bottom:

outlines:
  _raw:
    - what: rectangle
      where: /key/
      size: [ kx, kx ]
  _keys:
    - what: rectangle
      where: /key/
      size: [ kx-0.5, ky-0.5 ]

  baseplate:
    - what: rectangle
      where: matrix_indexfar_bottom
      size: [ 3 kx, 3 kx ]
      adjust:
        shift: [ 1.1, 19 ]
    - what: rectangle
      where: thumbs_layer_cluster
      size: [ 3.5kx,2kx ]
      adjust:
        shift: [ -2-kx, 0.5 kx - 0.6 ]
    - what: rectangle
      where: thumbs_space_cluster
      size: [ 2kx, 2.3 kx ]
      adjust:
        shift: [ 0, 12.4 ]
    - what: rectangle
      where: thumbs_space_cluster
      size: [ 1kx, 4 kx ]
      adjust:
        shift: [ kx, 9 ]
      operation: subtract
    - what: outline
      name: _raw
      operation: add
      expand: 1)

  combo:
    - what: outline
      name: baseplate
    - what: outline
      name: _keys
      operation: subtract

pcbs:
  prototype:
    template: kicad8
    outlines:
      main:
        outline: baseplate
    footprints:

      key_switches:
        what: ceoloide/switch_choc_v1_v2
        where: /key/
        params:
          reversible: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
          # The following parameters are specific to choc_v1_v2
          include_traces_vias: true
          outer_pad_width_front: 2.0
          outer_pad_width_back: 2.0
          choc_v2_support: true
          choc_v1_support: false
        adjust:
          rotate: 0

      diodes:
        what: ceoloide/diode_tht_sod123
        where: /key/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: false
          reversible: true
          side: F
        adjust:
          shift: [ 0, -5 ]
          rotate: 180

      mcu:
        what: ceoloide/mcu_nice_nano
        where: mcu
        params:
          P21: C0
          P20: C1
          P19: C2
          P18: C3
          P15: C4
          P14: C5
          P5: R0
          P6: R1
          P7: R2
          P8: R3
          reversible: true
          include_traces: true
          show_silk_labels: true
          show_via_labels: true
          show_instructions: false
          use_rectangular_jumpers: true
          only_required_jumpers: true
        adjust:
          shift: [ 0, 1 ]

      battery_jack:
        what: ceoloide/battery_connector_jst_ph_2
        where: mcu
        params:
          reversible: true
        adjust:
          rotate: 90
          shift: [ -7, -kx - 9]

      power_switch:
        what: ceoloide/power_switch_smd_side
        where: matrix_indexfar_bottom
        params:
          reversible: true
        adjust:
          rotate: 0
          shift: [ 1.5kx , 7]

      reset_button:
        what: ceoloide/reset_switch_tht_top
        where: mcu
        params:
          reversible: true
        adjust:
          rotate: 0
          shift: [ 0, -19 ]

      screws:
        what: ceoloide/mounting_hole_npth
        where: /screw/

      jlcpcb_order_number_text:
        what: ceoloide/utility_text
        where: mcu
        params:
          text: "JLCJLCJLCJLCJLCJLC"
          reversible : true
        adjust:
          rotate: 90
          shift: [ 0, -6 ]

      ergogen_logo:
        what: ceoloide/utility_ergogen_logo
        where: matrix_middle_bottom
        params:
          scale: 2.5
          reversible: true
        adjust:
          shift: [ 0, -1u ]