meta: 
  engine: 4.1.0

units:
  $default_width: 18
  $default_height: 17
  kx: cx
  ky: cy

  px: kx + 4
  py: ky + 4

points:
  key:
    padding: ky
    spread: 1kx
    footprints:
      choc_hotswap:
        type: choc
        nets:
          from: =column_net
          to: GND
        params:
          keycaps: true
          reverse: true
          hotswap: true
        choc:
          type: choc
          anchor:
            rotate: 180
          nets:
            from: =column_net
            to: GND
          params:
            keycaps: true
            reverse: true
  zones:
    matrix: # of keys
      anchor:
        shift: [100, -100] # Fix KiCad placement
      # Use the pins closer to the keys for the rows, and the pins farther from the keys for the columns
      columns: 
        outer:
          key:
            column_net: C0
        pinky: 
          key:
            column_net: C1
        ring:
          key:
            stagger: 5
            column_net: C2
        middle:
          key:
            stagger: 10
            column_net: C3
        index:
          key:
            stagger: -5
            column_net: C4
        indexfar:
          key:
            stagger: -2.5
            column_net: C5
      rows:
        bottom:
          row_net: R2
        home:
          row_net: R1
        top:
          row_net: R0
    thumbs:
      columns:
        layer:
          key:
            splay: -15
            column_net: C0
        space:
          key:
            splay: -15
            shift: [2,-2]
            column_net: C1
      anchor:
        ref: matrix_indexfar_bottom
        shift: [2,-ky - 3]
      rows:
        cluster:
          row_net: R3

outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  combo:
    - what: outline
      name: raw
      expand: 1)
    - what: outline
      name: keys
      operation: subtract






